---
# tasks file for install_imagequality
- name: Downloading image quality file
  get_url:
    url: https://storage.googleapis.com/jaak-artifact/packages/binarios/jaak-iq.tar.gz
    dest: /root/jaak/installer

- name: Extracting image quality file
  unarchive:
    src: /root/jaak/installer/jaak-iq.tar.gz
    dest: /root/jaak/installer/