- name: Install required packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

- name: Add Docker repo
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Enable Docker Edge & Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: "{{ item }}"
    option: enabled
    value: 0
  with_items: ['docker-ce-test', 'docker-ce-edge']

- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: $USER
    groups: docker
    append: yes
